# 生产环境配置
app:
  # 全局接口前缀
  globalApiPrefix: mock
  # 后端服务端口
  port: 3000
  # 日志相关
  logger: 
    level: debug
    maxFiles: 31
    # 项目日志存储路径，相对路径（相对本项目根目录）或绝对路径
    dir: '../logs'
jwt:
  secret: 'mock-jwt-secret'
  jwtExprire: 86400
swagger:
  enabled: false
  path: api-doc
redis:
  host: redis
  port: 6379
  password: ''
  db: 0
db:
  mysql:
    DATABASE_URL: "mysql://root:123456@mysql:3306/mock-api-db?schema=public"